# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b915e10b1bdb66a35a161921078714c0335a14f147e12a2df16914ccab006ef582e3aac02137fc6197b82f134a8dfd73656954b7acf83ae30382b080940d407

test:
  secret_key_base: 2d62a0bc52a5764cca12751cb514acb801cd9e78ff311815b4aae02a3d73e9a1f83f5e5b5290efaa8e61a460a6157bebddcc98a27283c4aa7f75f1025ccf6554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
